language: clojure
lein: lein2
env: 
 - TEST_DIR=register-user
 - TEST_DIR=register-user-req
 - TEST_DIR=gui-proxy
jdk:
  - oraclejdk8
script: cd $TEST_DIR && lein deps && lein test  
notifications:
  slack:
    rooms:
      - jkpg-dev:wSOeyWUF1M8bZXJpKSA6F0Nz#clojure-dojo
