language: clojure
env: 
 - TEST_DIR=register-user
 - TEST_DIR=register-user-req
 - TEST_DIR=gui-proxy
jdk:
  - oraclejdk8
script:
 - cd $TEST_DIR
 - lein2 deps
 - lein2 test  
notifications:
  slack:
    rooms:
      - jkpg-dev:wSOeyWUF1M8bZXJpKSA6F0Nz#clojure-dojo
